export const USERS_STATES = [
  {
    id: "1",
    name: "Mahmut",
    surname: "Yolcu",
    country: "Libya",
  },
  {
    id: "2",
    name: "Hanzade",
    surname: "Oflaz",
    country: "Lesotho",
  },
  {
    id: "3",
    name: "Güssem",
    surname: "Yordamlı",
    country: "Ermenistan",
  },
  {
    id: "4",
    name: "Ülke",
    surname: "Ar",
    country: "Brezilya",
  },
  {
    id: "5",
    name: "Lalegül",
    surname: "Cantürk",
    country: "Ruanda",
  },
  {
    id: "6",
    name: "Bahise",
    surname: "Ilkım",
    country: "Bangladeş",
  },
  {
    id: "7",
    name: "Garib",
    surname: "Göğebakan",
    country: "Ermenistan",
  },
  {
    id: "8",
    name: "Abdülvedud",
    surname: "Adaşlık",
    country: "Nepal",
  },
  {
    id: "9",
    name: "Rasiye",
    surname: "Bülbül",
    country: "Grönland",
  },
  {
    id: "10",
    name: "Zarafet",
    surname: "Sonkurt",
    country: "Tayland",
  },
  {
    id: "11",
    name: "Burhanettin",
    surname: "Çopur",
    country: "Gürcistan",
  },
  {
    id: "12",
    name: "Beklen",
    surname: "Birdal",
    country: "Tuvalu",
  },
  {
    id: "13",
    name: "Atahan",
    surname: "Özdil",
    country: "Finlandiya",
  },
  {
    id: "14",
    name: "Simber",
    surname: "Dertli",
    country: "Faroe Adalar",
  },
  {
    id: "15",
    name: "Mebsut",
    surname: "Akdaş",
    country: "Marshall Adaları",
  },
  {
    id: "16",
    name: "Sarim",
    surname: "Torgut",
    country: "Burundi",
  },
  {
    id: "17",
    name: "Dürüst",
    surname: "Başak",
    country: "Cebelitarık",
  },
  {
    id: "18",
    name: "Haman",
    surname: "Eseoğlu",
    country: "Yunanistan",
  },
  {
    id: "19",
    name: "Oktuna",
    surname: "Gülezgin",
    country: "Kazakistan",
  },
  {
    id: "20",
    name: "Yalabuk",
    surname: "Özbaş",
    country: "Yeni Kaledonya",
  },
  {
    id: "21",
    name: "Dursunali",
    surname: "Altıntaş",
    country: "Nikaragua",
  },
  {
    id: "22",
    name: "Karacan",
    surname: "Özçeker",
    country: "Finlandiya",
  },
  {
    id: "23",
    name: "Turna",
    surname: "Kalaycı",
    country: "Lesotho",
  },
  {
    id: "24",
    name: "Rami",
    surname: "Akdemir karaca",
    country: "Ermenistan",
  },
  {
    id: "25",
    name: "Nüvid",
    surname: "Kızılay",
    country: "Avustralya",
  },
  {
    id: "26",
    name: "Buhari",
    surname: "Kırıkçı",
    country: "Kenya",
  },
  {
    id: "27",
    name: "Özkutal",
    surname: "Yavuçkal",
    country: "Bangladeş",
  },
  {
    id: "28",
    name: "Cabbar",
    surname: "Özbek",
    country: "Virgin Adaları (ing.)",
  },
  {
    id: "29",
    name: "Usum",
    surname: "Tanır",
    country: "İngiltere",
  },
  {
    id: "30",
    name: "Kırtekin",
    surname: "Gelmez",
    country: "Ermenistan",
  },
  {
    id: "31",
    name: "Seher",
    surname: "Boran koşar",
    country: "Arjantin",
  },
  {
    id: "32",
    name: "İber",
    surname: "Kantarcı",
    country: "Bahama Adaları",
  },
  {
    id: "33",
    name: "Özsan",
    surname: "Altaş",
    country: "Somali",
  },
  {
    id: "34",
    name: "Tugay",
    surname: "Tektaş",
    country: "Togo",
  },
  {
    id: "35",
    name: "Samiye",
    surname: "Kolukısa",
    country: "Malezya",
  },
  {
    id: "36",
    name: "Teşci",
    surname: "Selçuk hekim",
    country: "Fildişi Kıyısı",
  },
  {
    id: "37",
    name: "İzlem",
    surname: "Kesgin çağlayan",
    country: "Guyana",
  },
  {
    id: "38",
    name: "İlkem",
    surname: "Demirkök",
    country: "Ekvador",
  },
  {
    id: "39",
    name: "Beyzade",
    surname: "Altınbaş",
    country: "Şili",
  },
  {
    id: "40",
    name: "Oğur",
    surname: "Kayış",
    country: "Gürcistan",
  },
  {
    id: "41",
    name: "Yura",
    surname: "Gövercin",
    country: "Malavi",
  },
  {
    id: "42",
    name: "Gizem",
    surname: "Yalçınsoy",
    country: "Grönland",
  },
  {
    id: "43",
    name: "Tabende",
    surname: "Bozak",
    country: "Macaristan",
  },
  {
    id: "44",
    name: "Vamıka",
    surname: "Gökçeler",
    country: "Aruba",
  },
  {
    id: "45",
    name: "Sargut",
    surname: "Sevinçhan",
    country: "Maldiv Adaları",
  },
  {
    id: "46",
    name: "Lina",
    surname: "Kalaycıoğlu",
    country: "Maldiv Adaları",
  },
  {
    id: "47",
    name: "Oktuna",
    surname: "Alkış",
    country: "Liechtenstein",
  },
  {
    id: "48",
    name: "Beliz",
    surname: "Akel",
    country: "Gine-Bissau",
  },
  {
    id: "49",
    name: "Zeval",
    surname: "Oruçoğlu",
    country: "Irak",
  },
  {
    id: "50",
    name: "Ferhat",
    surname: "Canpolat onay",
    country: "Venezuela",
  },
];
